import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/curso/nr-12")({ component: CursoNR12 });

function CursoNR12() {
  const CONTEUDO = ["Princípios de segurança em máquinas e equipamentos","Principais riscos e medidas de prevenção","Dispositivos e sistemas de segurança","Procedimentos seguros de operação","Cuidados durante manutenção e intervenções","Responsabilidades de trabalhadores e empregadores"];
 return <main style={{minHeight:"100vh",background:"#f5f7fa",color:"#172033",fontFamily:"Arial, Helvetica, sans-serif"}}>
  <header style={{background:"#fff",borderBottom:"1px solid #e5e7eb"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"18px 24px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><a href="/"><img src="/logo-ibrast.svg" alt="IBRAST" style={{width:170,height:44,objectFit:"contain"}}/></a><a href="https://dashboard.kiwify.com/courses" target="_blank" rel="noreferrer" style={{height:42,padding:"0 20px",border:"1px solid #1769e0",borderRadius:8,color:"#1769e0",fontWeight:700,display:"inline-flex",alignItems:"center",textDecoration:"none"}}>Área do Aluno</a></div></header>
  <section style={{maxWidth:1100,margin:"0 auto",padding:"55px 24px 45px",display:"grid",gridTemplateColumns:"1.05fr .95fr",gap:45,alignItems:"center"}}><div><div style={{display:"inline-block",padding:"7px 12px",borderRadius:999,background:"#e8f1ff",color:"#1769e0",fontSize:13,fontWeight:800,marginBottom:18}}>CURSO ONLINE • NR-12</div><h1 style={{margin:0,fontSize:40,lineHeight:1.12}}>NR-12 — Segurança no Trabalho em Máquinas e Equipamentos</h1><p style={{margin:"18px 0 0",fontSize:19,lineHeight:1.55,color:"#475467"}}>Capacitação voltada à segurança na operação, manutenção e utilização de máquinas e equipamentos, com foco na prevenção de acidentes.</p><a href="#comprar" style={{marginTop:28,height:50,padding:"0 28px",borderRadius:8,background:"#1769e0",color:"#fff",fontWeight:800,display:"inline-flex",alignItems:"center",textDecoration:"none"}}>QUERO FAZER O CURSO</a></div><div style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:16,overflow:"hidden"}}><img src="https://i.postimg.cc/Wb3bhh1q/NR-12.png" alt="Capa NR-12" style={{width:"100%",display:"block",objectFit:"cover"}}/></div></section>
  <section style={{background:"#fff",borderTop:"1px solid #e5e7eb",borderBottom:"1px solid #e5e7eb"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"48px 24px"}}><h2 style={{margin:"0 0 14px",fontSize:30}}>Por que fazer este curso?</h2><p style={{maxWidth:850,margin:0,color:"#475467",fontSize:17,lineHeight:1.7}}>Tenha uma capacitação online, organizada e acessível para estudar de onde estiver, sem precisar interromper sua rotina para se deslocar até uma sala de treinamento.</p></div></section>
  <section style={{maxWidth:1100,margin:"0 auto",padding:"48px 24px"}}><h2 style={{margin:"0 0 24px",fontSize:30}}>O que você vai aprender</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:16}}>{[<div key={x} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:10,padding:"18px 20px",fontWeight:700,lineHeight:1.45}}><span style={{color:"#1769e0",marginRight:8}}>✓</span>{x}</div>)}</div></section>
  <section style={{background:"#eef5ff",borderTop:"1px solid #dbeafe",borderBottom:"1px solid #dbeafe"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"48px 24px"}}><h2 style={{margin:"0 0 26px",fontSize:30}}>Sem tempo para um treinamento presencial?</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:18}}>{[["⏰","Estude no seu horário","Faça sua capacitação online no momento que for melhor para você."],["💻","Acesso online","Estude pelo computador ou celular, de onde estiver."],["📚","Conteúdo objetivo","Material organizado para facilitar seu estudo."],["🎓","Certificado","Após concluir o treinamento, tenha acesso ao seu certificado."]].map(([i,t,x])=><div key={t} style={{background:"#fff",borderRadius:12,padding:22}}><div style={{fontSize:28,marginBottom:10}}>{i}</div><div style={{fontWeight:800,marginBottom:7}}>{t}</div><div style={{color:"#667085",fontSize:14,lineHeight:1.55}}>{x}</div></div>)}</div></div></section>
  <section id="comprar" style={{maxWidth:1100,margin:"0 auto",padding:"55px 24px 70px"}}><div style={{background:"#111827",color:"#fff",borderRadius:16,padding:"38px 30px",textAlign:"center"}}><div style={{fontSize:13,fontWeight:800,letterSpacing:1.5,color:"#93c5fd"}}>NR-12</div><h2 style={{margin:"10px 0 12px",fontSize:32}}>Pronto para fazer sua capacitação?</h2><p style={{margin:"0 auto 24px",maxWidth:650,color:"#cbd5e1",lineHeight:1.6}}>Comece sua capacitação online e estude de onde estiver, no seu ritmo. Ao concluir o treinamento, receba seu certificado.</p><a href="#" style={{height:50,padding:"0 32px",borderRadius:8,background:"#1769e0",color:"#fff",fontWeight:800,display:"inline-flex",alignItems:"center",textDecoration:"none"}}>COMPRAR CURSO</a></div></section>
  <footer style={{background:"#111827",color:"#fff",borderTop:"1px solid #1f2937"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"42px 24px 26px",display:"grid",gridTemplateColumns:"minmax(260px,1.5fr) repeat(2,minmax(170px,1fr))",gap:40}}><div><div style={{marginBottom:14,color:"#fff",fontSize:28,fontWeight:800,letterSpacing:1}}>IBRAST</div><p style={{margin:0,maxWidth:360,color:"#cbd5e1",fontSize:14,lineHeight:1.7}}>Consiga seu certificado sem complicação. Faça sua capacitação online, de onde estiver, em qualquer dia e horário, e após a conclusão receba seu certificado imediatamente.</p></div><div><div style={{fontWeight:800,marginBottom:14}}>Cursos</div><div style={{display:"grid",gap:8,fontSize:14}}>{["05","06","11","12","18","33","35"].map(x=><a key={x} href={"/curso/nr-"+x} style={{color:"#cbd5e1",textDecoration:"none"}}>NR {x}</a>)}</div></div><div><div style={{fontWeight:800,marginBottom:14}}>Acesso</div><div style={{display:"grid",gap:10}}><a href="https://dashboard.kiwify.com/courses" target="_blank" rel="noreferrer" style={{color:"#cbd5e1",textDecoration:"none",fontSize:14}}>Área do Aluno</a><span style={{color:"#94a3b8",fontSize:14}}>Acesso online aos seus cursos</span><span style={{color:"#94a3b8",fontSize:14}}>Certificado ao concluir</span></div></div></div><div style={{borderTop:"1px solid #1f2937",maxWidth:1100,margin:"0 auto",padding:"16px 24px",display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:12,color:"#94a3b8",fontSize:12}}><span>© {new Date().getFullYear()} IBRAST. Todos os direitos reservados.</span><span>Pagamento e acesso processados pela Kiwify.</span></div></footer>
 </main>;
}